import OpenAI from 'openai'
import { config } from '../config/env.js'

// The chatbot's LLM — every one of Martini's replies is generated by OpenAI.
export const openai = new OpenAI({ apiKey: config.openai.apiKey })

// Pull the assistant's text out of a chat-completion response.
export const textOf = (completion) => completion?.choices?.[0]?.message?.content || ''
